### ISSUE TITLE
Link Discord invite offline

### ISSUE THREAD

**Issue by HakaCode** [Liga-dos-Programadores/liga-landing#1]
Link para o convite do servidor discord esta off, eu gostaria de entrar no servidor se possível.

![download](https://user-images.githubusercontent.com/33907565/87490413-072d1380-c61c-11ea-8664-7e224376dfe0.png)

**Comment by beescuit** [comment]
Fixed in 0b134944124262f5a3044d3e60dd7dcbc7b8a82b
